name: Test

on:
  push:
    branches:
    - master
    - develop
  pull_request:

env:
  WEB3_INFURA_PROJECT_ID: ${{ secrets.WEB3_INFURA_PROJECT_ID }}

jobs:
  sett-simulation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Cache Compiler Installations
      uses: actions/cache@v2
      with:
        path: |
          ~/.solcx
          ~/.vvm
        key: compiler-cache

    - name: Cache compiler installations
      uses: actions/cache@v2
      with:
        path: |
          ~/.solcx
          ~/.vvm
        key: ${{ runner.os }}-compiler-cache

    - name: Install ganache
      run: npm install -g ganache-cli@6.11

    - name: Set up python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Set pip cache directory path
      id: pip-cache-dir-path
      run: |
        echo "::set-output name=dir::$(pip cache dir)"

    - name: Install python dependencies
      run: pip install -r requirements.txt

    - name: Run Digg Simulation Tests
      run: brownie test tests/sett/test_digg_simulation.py
